### ISSUE TITLE
Error while installing keystone

### ISSUE THREAD

**Issue by albertinisg** [ging/fiware-idm-deprecated#3]
Hi!

We are installing `fi-ware-idm` for developing a [devguide](https://github.com/Bitergia/fiware-devguide-app) and since last week we are having issues installing keystone.

It seems that following the `requirements.txt` it's installing a newer version (2.0.0) so it cannot find the required one, showing this trace:

```
Traceback (most recent call last):
  File "/opt/virtualenvs/idm_tools/local/lib/python2.7/site-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/opt/virtualenvs/idm_tools/local/lib/python2.7/site-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/opt/fi-ware-idm/fabfile.py", line 17, in <module>
    from deployment import keystone
  File "/opt/fi-ware-idm/deployment/keystone.py", line 25, in <module>
    from keystoneclient.v3 import client
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/__init__.py", line 34, in <module>
    from keystoneclient import client
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/client.py", line 13, in <module>
    from keystoneclient import discover
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/discover.py", line 22, in <module>
    from keystoneclient.v2_0 import client as v2_client
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/v2_0/client.py", line 23, in <module>
    from keystoneclient.v2_0 import ec2
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/v2_0/ec2.py", line 16, in <module>
    from keystoneclient import base
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/base.py", line 31, in <module>
    from keystoneclient.openstack.common.apiclient import base
  File "/opt/virtualenvs/idm_tools/src/fiwareclient/keystoneclient/openstack/common/apiclient/base.py", line 29, in <module>
    from oslo.utils import strutils
ImportError: No module named oslo.utils
```

Tried to install manually one of the allowed ones (1.4.0) and we were able to installing but, is not working at all.

Which is the version we should use for this? Any help would be apreciated.

Thanks in advance!

**Comment by garcianavalon** [comment]
Hi!
there is an on going namespace change in the openstack libraries so errors like this appear from time to time lately.
I'll fix it and upload a patch ASAP.

thanks for reporting the error.

**Comment by garcianavalon** [comment]
fixed, it should install correctly now https://github.com/ging/python-keystoneclient/commit/55c6be6cdffc1928e0354fe3b5b9c76e654dc94d

**Comment by albertinisg** [comment]
Worked perfectly! Thanks a lot for the super fast fix :)

**Comment by albertinisg** [comment]
I've been testing it and as said before, installation was successful but it's still not working. Whenever I try to access the IdM, apache throws an error:

```
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

Following this instructions, we can find that the `error.log` shows the following:

```
[Mon Jul 27 15:37:08.757622 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204] mod_wsgi (pid=99): Exception occurred processing WSGI script '/opt/fi-ware-idm/horizon/openstack_dashboard/wsgi/django.wsgi'., referer: https://idm/
[Mon Jul 27 15:37:08.757694 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204] Traceback (most recent call last):, referer: https://idm/
[Mon Jul 27 15:37:08.757715 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]   File "/opt/fi-ware-idm/horizon/.venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__, referer: https://idm/
[Mon Jul 27 15:37:08.757889 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]     self.load_middleware(), referer: https://idm/
[Mon Jul 27 15:37:08.757906 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]   File "/opt/fi-ware-idm/horizon/.venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware, referer: https://idm/
[Mon Jul 27 15:37:08.758032 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]     for middleware_path in settings.MIDDLEWARE_CLASSES:, referer: https://idm/
[Mon Jul 27 15:37:08.758045 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]   File "/opt/fi-ware-idm/horizon/.venv/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__, referer: https://idm/
[Mon Jul 27 15:37:08.758138 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]     self._setup(name), referer: https://idm/
[Mon Jul 27 15:37:08.758149 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]   File "/opt/fi-ware-idm/horizon/.venv/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup, referer: https://idm/
[Mon Jul 27 15:37:08.758172 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]     self._wrapped = Settings(settings_module), referer: https://idm/
[Mon Jul 27 15:37:08.758181 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]   File "/opt/fi-ware-idm/horizon/.venv/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__, referer: https://idm/
[Mon Jul 27 15:37:08.758198 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204]     % (self.SETTINGS_MODULE, e), referer: https://idm/
[Mon Jul 27 15:37:08.758219 2015] [:error] [pid 99:tid 140244825396992] [client 172.17.42.1:52204] ImportError: Could not import settings 'openstack_dashboard.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named oslo.config, referer: https://idm/
```

Which seems to be an error with another module. Probably something related with the one I reported :)

**Comment by garcianavalon** [comment]
True. This rename issue is a headache... I have a fix already uploaded

**Comment by garcianavalon** [comment]
Fix uploaded  for Horizon https://github.com/ging/horizon/commit/3c980b767cb70e38c221534183b308d0af05cdf6

I recommend you to run `sudo python tools/install_venv.py` and update all of the dependencies, as some of them were causing the issue and need an upgrade.

**Comment by albertinisg** [comment]
Tested and worked perfectly. Again, thanks a lot!

**Comment by gelas** [comment]
This is great. Had the same problem for few days.
Thanks.
